apiVersion: v1
kind: Pod
metadata:
  name: goweb
  labels:
    app: goweb 
spec:
  containers:
    - name: goweb 
      image: gcr.io/python-153404/goweb:0.0.1
      ports:
        - name: tcp
          containerPort: 8080
      resources:
        limits:
          cpu: 0.1
          memory: "4Mi"
